dist: bionic
language: c
matrix:
  include:
    - compiler: clang
      os: linux
    - compiler: gcc
      os: linux

script:
  ./autogen.sh;
  ./configure;
  make -k;
  make distcheck;
  mkdir rpki-cache rpki;
  src/rpki-client -v -t afrinic.tal -t apnic.tal -t lacnic.tal -t ripe.tal -d rpki-cache rpki
